const Data = [
  {
    id: 1,
    img: "/src/assets/images/man1.jpg",
    name: "Ed Silas",
    email: "sislasedikan@gmail.com",
    gender: "male",
    city: "Abuja",
  },
  {
    id: 2,
    img: "/src/assets/images/woamn1.webp",
    name: "Helen Chiyere",
    gender: "female",
    email: "chiyerehelen@gmail.com",
    city: "Delta",
  },
  {
    id: 3,
    img: "/src/assets/images/man3.jpg",
    name: "Seun Agustus",
    email: "seunagustus@gmail.com",
    gender: "male",
    city: "Lagos",
  },
  {
    id: 4,
    img: "/src/assets/images/woaman2.webp",
    name: "Anita Gibbs",
    gender: "female",
    email: "gibsanita@gmail.com",
    city: "Benin City",
  },
  {
    id: 5,
    img: "/src/assets/images/woman3.jpeg",
    name: "Emem Edem",
    email: "edememem@gmail.com",
    gender: "female",
    city: "Uyo",
  },
  {
    id: 6,
    img: "/src/assets/images/man2.jpg",
    name: "Mike Adeleke",
    email: "adelekemike@gmail.com",
    gender: "male",
    city: "Ibadan",
  },
  {
    id: 7,
    img: "/src/assets/images/woman4.webp",
    name: "Nadia Micheal",
    email: "nadianana@gmail.com",
    gender: "female",
    city: "Jos",
  },
  {
    id: 8,
    img: "/src/assets/images/man6.jpeg",
    name: "Ike Arinze",
    email: "arinzeike@gmail.com",
    gender: "male",
    city: "Port Harcourt",
  },
  {
    id: 9,
    img: "/src/assets/images/woman5.webp",
    name: "Alima Humammed",
    email: "alimaamed@gmail.com",
    gender: "female",
    city: "Kano",
  },
];

export default Data;
